//英文语言包
var English = {
  content: "this is english",
  notlogged: "Tap the avatar above to login",
  submitt: "Submit",
  changelanguagebutton: "去中文版小程序",
  association: "Tsinghua Students' Tennis Association",
  signup: "Sign up for matches",
  myassociation: "My Association",
  manage: "Manage",
  record: "Ma Yuehan Cup",
  settings: "Settings",
  newmatch: "New/Modify Match",
  updatedraw: "Update Draw",
  enterscore: "Enter Score",
  moreinfobutton: "More Info",
  signupbutton: "Sign up",
  signupnowbutton: "Sign up Now",
  underconstruction: "Page is now under construction",
  inputid: "Your ID (Student ID)",
  inputpwd: "Your Password",
  inputrealname: "Your Real Name",
  inputphoneno: "Phone No. when Registered",
  inputuid: "ID when Registered",
  inputnewpwd: "New Password",
  submitreq: "Submit Request",
  underconstruction: "Page is now under construction",
  loginbtn: "Login",
  registerbtn: "Register",
  nopermitformanage: "You don't have enough permission to manage matches",
  nopermitformanageusers: "You don't have enough permission to manage users",
  manageusers: "New Members",
  notinthegroup: "You are not yet a member",
  notinthegroup2: " of TSTA this semester. You can:",
  jointhegroupbtn: "Join Now",
  knowmore: "Know more about us",
  nomatch: "Currently no match!",

  notopen: "Registration not open right now. Please join us on our stand during registration time.",
  joinnote: "Note: The Tennis Association will hand in the information of yours to the department of student associations of our unversity. Please make sure the following information are precise.",
  endnote1: "If there's any error in these information, please go to Settings to modify it.",
  endnote2: "If all the info above is correct, please go on finishing the following info:",

  levelestimate: "Feel free to ask us about details of the levels! Or you can determine your level by the following criteria:",
  levelbeginner: "A.Beginner. Never/Almost never have played before;",
  levelintermediate: "B.Intermediate. Have been playing for a while, but lack of consistency and depth of shots;",
  leveladvanced: "C.Advanced. Have been playing for at least one year, but still need instructions in serving, volleying, etc. and lack of consideration in tactics;",
  levelveteran: "D.Do not need coaching. Just looking for someone in the same level to play together.",
  becomeofficer: "Would you like to join us and become an officer in the Tennis Association?",
  thursfull: "Thursday session is now full, please sign up for other sessions!",
  satfull: "Saturday session is now full, please sign up for other sessions!",
  success: "You have become a member!",
  submitsuccess1: "Your application is submitted",
  submitsuccess2: "YET NOT COMPLETED",
  submitsuccess3: "Please join the members' Wechat group & pay your membership fee on site. Once completed these two steps, contact our officer to approve your application!",

  beforesubmit: "Please double check all your info are correct!",
  submitinfo: "SUBMIT",

  info_email: "E-mail",
  info_realname: "Realname: ",
  info_gender: "Gender: ",
  info_phone: "Phone No.: ",
  info_department: "Department: ",
  info_grade: "Grade: ",
  info_stuid: "Student ID: ",
  info_classdate: "Session",
  info_rating: "Level",
  info_wechatid: "WechatID",
  ph_email: "example@server.domain",

  submitwarning1: "Please double check your session time. You have chosen ",
  submitwarningthurs: "Thursday Sessions. ",
  submitwarningsat: "Saturday Sessions. ",
  submitwarning2: "Once you submit the application, the session time cannot be changed! Proceed?",
  modalyes: "Yes",
  modalno: "No",

  thursdaymember: "Member of Thursday Sessions, 2021 Spring",
  saturdaymember: "Member of Saturday Sessions, 2021 Spring",
  
  remainingactionpoints: "Number of Activities Left: ",

  erl_title: "Join Tennis Association",
  erl_titleb: "For This Semester!",
  erl_welcome: "Welcome to join Tsinghua Students' Tennis Association!",
  erl_intro: "Tsinghua Students’ Tennis Association (TSTA) is aimed to provide better service for all tennis lovers in the campus. During the semester, TSTA will organize two sets of training sessions for members on Thursdays and Saturdays, respectively. Each member can only enroll in one training session (either Thursday or Saturday). There are 8 activities for each session. Activities on Thursday are from 4 to 6 pm（from 3pm to 5pm in winter), and Saturday from 10 to 12 am. To ensure the quality of the activities and to allow more students to participate, the number of members for each activity will be limited within 60.",
  erl_coach: "We will hire Tsinghua-Tennis-Team level players as coaches for the activities. Coaches will provide according guidance for A, B, and C level members, from beginners to advanced players. For D level members(veterans), we only provide courts and members in the same level for you to play with. If you’re interested in becoming a coach and earn some extra, please consult our officers.",
  erl_title1: "About Weekly Training Sessions:",
  erl_q1: "Q1: Do I need to pay membership fee? What can I get from being a member?",
  erl_a1: "A: We are a non-profit organization. However, we need to charge a membership fee to pay for the courts, balls and coaching. The fee is ￥150 per person per semester.",
  erl_q2: "Q2: How can I confirm that I have enrolled successfully?",
  erl_a2: "A: You will be asked to join a member group in Wechat by scanning a QR code at the enrolling site. After that, please check“My Association” in this Miniprogram, if it says “You have become a member!”, your enrollment is complete!",
  erl_q3: "Q3: What is the difference between those A, B, C and D levels?",
  erl_a3: "To make sure that everyone can find partners of similar level, we set four different levels. You will need to assess your own tennis level and then choose one at the enrolling site. The following descriptions provide a vague rule of assessment, and please consult our officers on site if you have any questions.",
  erl_levelA: "A.Beginner. Never/Almost never have played before. Our coaches will familiarize you with tennis from the basics, including rackets, courts, grips, forehand and backhand. you can also pair up freely and practice your tennis skills.",
  erl_levelB: "B.Intermediate. Have been playing for a while, but lack of consistency and depth of shots, especially players who has only been playing less than a year. Our coaches will help you to improve your skills by doing certain drills. In the last four activities, you can also pair up freely and practice your tennis skills.",
  erl_levelC: "C.Advanced. Have been playing for at least one year, but still need instructions in serving, volleying, etc. and lack of consideration in tactics. Our coaches will provide instructions for harder tactics, and also organize same level players and held tiny matches.",
  erl_levelD: "D.Do not need coaching. Just looking for someone in the same level to play together. We don't provide coaches for this level players. You can use our courts, find same level players here, and improve on your own.",
  erl_q4: "Q4: What level can I reach after a semester’s training session? Can I play good rallies then?",
  erl_a4: "A: If you attend each activity and practice a lot after class, you will definitely play better tennis than you did before. If you are a beginner, we expect to help you reach a level that you can hit shots with some control after a semester’s training. But don’t expect to play like professionals just after a semester’s training. Practice makes perfect!",
  erl_q5: "Q5: I don't have a tennis racquet yet. Do you know where I can get one?",
  erl_a5: "A: To make it easy and convenient for you to get a tennis racquet in a fair price, we organize group purchases for you. Please ask our officers for more information about it.",
  erl_q55: "Q6: Can I change the session time after today?(e.g. from Thursday sessions to Saturdays) Also, can I change the level after today?(e.g. from level A to level B)",
  erl_a55: "A: We're sorry but the session time is not switchable. If you do have an emergency that you want to swap the time slot, you need to post a request in the Wechat group to ask for someone who's willing to swap with you. However, the level is free for you to change. You'll find 3 coaches each session for A/B/C level. Feel free to change coach whenever you feel that the content is too easy/hard!",
  erl_title2: "",
  erl_q6: "",
  erl_a6: "",
  erl_q7: "",
  erl_a7: "",
  erl_title3: "About Competition & Joining the Tennis Team:",
  erl_q8: "Q7: I am not content with just playing for fun. How do I participate in a competition?",
  erl_a8: "A: We will organize a tennis tournament during the semester as we did every year before. Everyone can enroll as individual. More detail for the tournament will be issued later. Please follow the TSTA official account in Wechat for more information.",
  erl_q9: "Q8: I am quite confident in my tennis skills. How do I join the university tennis team?",
  erl_a9: "A: Tsinghua Tennis Team have been cooperating with TSTA for a long time. Now quite a few players in the tennis team are originally from TSTA. If you demonstrate your passion and good level of tennis in TSTA, you will have great chance of being introduced to the tennis team.",
  erl_ending: "If you have further questions, we welcome you to ask us in the member Wechat group or consult us directly. We sincerely hope that you can find your court of happiness in our association!",
  erl_infonum: "Follow Tsinghua Tennis Association and get more updates about us!",

  contactus: "Contact us",
  modifypi: "Modify personal info",
  changepwd: "Request to reset password",
  logout: "Logout",

  tstawechat: "↑↑↑Follow us for more info!",

  tstaleader1: "Tennis Assoc: thutennis@126.com",
  tstaleader2: "Developer: pgmercxtn@gmail.com",
  tstacontact: "",

  gui_warning: "Warning: Despite we won't leak your personal information on purpose, you and Tsinghua Students' Tennis Association are not obliged by any official confidential agreement. So please don't use any password identical to your any other account's.(e.g. Wechat, Google, Facebook, Tsinghua info, etc.)",

  gui_realname: "Real Name",
  gui_stuid: "Univ. ID",
  gui_stuidph: "Student ID or Employee ID",
  gui_pwd: "Password",
  gui_pwdph: "6~20 any characters",
  gui_gender: "Gender",
  gui_ntrp: "NTRP level",
  gui_school: "University",
  gui_schoolph: "Tsinghua Univ.",
  ntrphint: "Hint: If you don't know what NTRP is, leaving it '1.0' is just fine.",
  gui_department: "Department",
  gui_departmentph: "Department of XXX",
  gui_grade: "Grade",
  gui_gradeph: "e.g.1st year Bachelor;2nd year Master;3rd year Doctor",
  gui_phone: "Phone No.",
  gui_phand: "Forehand",
  gui_bhand: "Backhand",
  bhandhint: "Hint: If you haven't played tennis, leaving it 'double-handed backhand' is just fine.",
  
  confirmtext: "OK",
  modalwarning: "Warning",
  reqlogin: "Please login first!",
  completepersonalinfo: "Please complete the information required.",
  modalhint: "Success",
  registersuccess: "Register success! Please tap the void avatar on the new page to login.",
  modalsubmitsuccess: "Submit success. Please remeber to pay membership fee, join WeChat group, and contact our officer!",

  tab_today: "Today",
  tab_m1day: "Yes.day",
  tab_groupstandings: "RR",
  tab_search: "Search",

  nomatchpermit1: "This feature is not opened to your user level",
  nomatchpermit2: "to reduce the risk of database overflow",
  nomatchpermit3: "Please make sure that you are logged in",
  courtpick: "Court: ",
}


//模块化
module.exports = {
  content: English
}